// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNFpwWw6XL4m2h89EgSD-TV2f0CGT8aWQ',
    appId: '1:659409368282:web:0c276f270edecb7bf5e1e3',
    messagingSenderId: '659409368282',
    projectId: 'up2btangki',
    authDomain: 'up2btangki.firebaseapp.com',
    storageBucket: 'up2btangki.appspot.com',
    databaseURL: 'https://up2btangki-default-rtdb.asia-southeast1.firebasedatabase.app',
    measurementId: 'G-ZS6H51SV2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb-W1QoGDn-RxgFv18LmfuhMeWimGnxOY',
    appId: '1:659409368282:android:403abf7f5696ade8f5e1e3',
    messagingSenderId: '659409368282',
    projectId: 'up2btangki',
    storageBucket: 'up2btangki.appspot.com',
    databaseURL: 'https://up2btangki-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAPyMJUez6a9DLjjDYN9F0PvkTWOl2EZQ',
    appId: '1:659409368282:ios:db9cc78ed340565ef5e1e3',
    messagingSenderId: '659409368282',
    projectId: 'up2btangki',
    storageBucket: 'up2btangki.appspot.com',
    iosBundleId: 'com.example.up2btangki',
    databaseURL: 'https://up2btangki-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAPyMJUez6a9DLjjDYN9F0PvkTWOl2EZQ',
    appId: '1:659409368282:ios:db9cc78ed340565ef5e1e3',
    messagingSenderId: '659409368282',
    projectId: 'up2btangki',
    storageBucket: 'up2btangki.appspot.com',
    iosBundleId: 'com.example.up2btangki',
    databaseURL: 'https://up2btangki-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNFpwWw6XL4m2h89EgSD-TV2f0CGT8aWQ',
    appId: '1:659409368282:web:f54d927d5f9a6f47f5e1e3',
    messagingSenderId: '659409368282',
    projectId: 'up2btangki',
    authDomain: 'up2btangki.firebaseapp.com',
    storageBucket: 'up2btangki.appspot.com',
    measurementId: 'G-0P1KSVFZQR',
    databaseURL: 'https://up2btangki-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
